#!/bin/bash

icons=`defaults read com.apple.finder CreateDesktop 2> /dev/null`

shopt -s nocasematch
case "$icons" in
  "" | "1" | "true" | "yes" | "on" )
    defaults write com.apple.finder CreateDesktop 0 && killall Finder;;
  * )
    defaults write com.apple.finder CreateDesktop 1 && killall Finder;;
esac
