#!/usr/bin/env bash

DICT_DIR="$(dirname "$(readlink -f "$0")")"

wordnum=4

specialchars="!@#$%^&*?;:~"
chrlen=$((${#specialchars} - 1))

words=( $(shuf --random-source=/dev/urandom -r -n "$wordnum" < $DICT_DIR/passgen.dic) )

password=""
for word in "${words[@]}"
do
    num=$(shuf --random-source=/dev/urandom -i 0-9 -n 1)
    key=$(shuf --random-source=/dev/urandom -i 0-"$chrlen" -n 1)
    special=${specialchars:key:1}
    password+="-$num${word^}$special"
done 
password=${password:1}

if command -v xclip > /dev/null; then
    xclip_present=true;
fi
if command -v wl-copy > /dev/null; then
    wlcopy_present=true;
fi

if [ $XDG_SESSION_TYPE = "wayland" ]
then
    if [ "$wlcopy_present" = true ]; then
        clipcommand="xargs wl-copy"
    else
        echo "ERROR: please install wl-clipboard to use this script in a Wayland session."
        exit 42
    fi
else
    if [ "$xclip_present" = true ]; then
        clipcommand="xclip -i -sel clip"
    else
        echo "ERROR: please install xclip to use this script in an X11 session."
        exit 42
    fi
fi

eval "echo '$password' | $clipcommand"
