#!/usr/bin/env bash

wordnum=4

specialchars="!@#$%^&*?;:~"
chrlen=$((${#specialchars} - 1))

words=( $(shuf --random-source=/dev/urandom -r -n "$wordnum" < passgen.asc) )

password=""
for word in "${words[@]}"
do
    num=$(shuf --random-source=/dev/urandom -i 0-9 -n 1)
    key=$(shuf --random-source=/dev/urandom -i 0-"$chrlen" -n 1)
    special=${specialchars:key:1}
    password+="-$num${word^}$special"
done 
password=${password:1}

clipcommand="xclip -i -sel clip"

if [ $XDG_SESSION_TYPE = "wayland" ]; then
    clipcommand="xargs wl-copy"
fi

eval "echo '$password' | $clipcommand"
