#!/usr/bin/env bash
# 
# This script reads the last modification date of a file and 
# prepends it to the name of the file. If invoked without additional
# parameters, the date is formatted as "%Y-%m-%d". If invoked with the
# optional parameter '-t', the date is formatted as "%Y-%m-%dT%H-%M".
#
# For example:
# % tstamp abc.txt    -> 2023-09-01_abc.txt
# % tstamp abc.txt -t -> 2023-09-01T07-40_abc.txt

fname=$(basename "$1")
fdir=$(dirname "$1")

if [ -z "$1" ]; then
	echo "USAGE: tstamp <filename> [-t]"
	exit 0
fi

if ! [ -f "$1" ]; then
	echo "ERROR: '$1' is not a file."
	exit 45
fi

timeopt="$2"

if [ "x${timeopt}" = "x-t" ]; then
	datetime="$(date -r "$1" '+%Y-%m-%dT%H-%M')"
else
	datetime="$(date -r "$1" '+%Y-%m-%d' )"
fi

newfname="${datetime}_${fname}"

echo "Original name: '${fdir}/${fname}'."
echo "Renaming to: '${fdir}/${newfname}'..."

mv "$fdir/$fname" "$fdir/$newfname"
