#!/usr/bin/env bash

if command -v xclip > /dev/null; then
    xclip_found=true
fi

if [ "$xclip_found" = true ]; then
    url=$( xclip -o -sel clip | cut -d '?' -f1 )
else
    echo "ERROR: xclip not found."
    exit 42
fi

if [ "x$1" = "xgo" ]; then
    echo "$url" | xargs firefox
else 
    echo "$url" | xclip -i -sel clip
fi
